
  /* ================= Uitbreiding: nieuwe helden ================= */
  // ---- Uncommon ----
  { id: 'munt', name: 'Muntmagnaat', rarity: 'uncommon', role: 'Geld', title: 'Miljonair met een missie', style: 'projectile', cost: 220,
    desc: 'Schiet gouden munten en levert elke golf extra geld op. Kills van hem geven een bonus.',
    base: { dmg: 8, range: 2.6, rate: 1.2, air: true, projSpeed: 14, income: 30, bounty: 0.3 },
    look: { skin: '#f1c27d', suit: '#15803d', suit2: '#facc15', cape: '#166534', hair: 'cap', hairC: '#facc15', emblem: 'dollar', weapon: 'orb', orb: '#facc15' },
    fx: 'gold', proj: 'coin', ability: 'goldrush',
    upgrades: [
      U('Spaarpot', 120, '+25 geld per golf', { income: 25 }),
      U('Premiejager', 200, 'Kills leveren 30% extra geld op, +4 schade', { bounty: 0.3, dmg: 4 }),
      U('Gouden Kluis', 400, '+50 geld per golf, munten doorboren 1 vijand', { income: 50, pierce: 1 }, true),
      U('Rente op Rente', 600, '+40 geld per golf, +0.4 snelheid', { income: 40, rate: 0.4 }),
      U('Beursgoeroe', 1200, '+100 geld per golf, kills +50% geld. ULTIMATE', { income: 100, bounty: 0.5, dmg: 10 }, true),
    ] },
  { id: 'medic', name: 'Veldarts', rarity: 'uncommon', role: 'Support', title: 'Houdt het team op de been', style: 'projectile', cost: 230,
    desc: 'Maakt helden in de buurt sneller en herstelt na elke golf wat basis-HP.',
    base: { dmg: 7, range: 2.4, rate: 1, air: true, projSpeed: 14, buffRange: 2, buffRate: 0.12, heal: 2 },
    look: { skin: '#e0ac69', suit: '#f8fafc', suit2: '#ef4444', cape: null, hair: 'long', hairC: '#78350f', emblem: 'cross', weapon: 'orb', orb: '#fca5a5' },
    fx: 'star', proj: 'bullet', ability: 'rally',
    upgrades: [
      U('Adrenaline', 130, 'Helden in de buurt +8% extra aanvalssnelheid', { buffRate: 0.08 }),
      U('Verbandtas', 220, 'Herstelt 3 extra basis-HP per golf', { heal: 3 }),
      U('Veldhospitaal', 420, 'Groter buffbereik, helden in de buurt +10% schade', { buffRange: 0.8, buffDmg: 0.1 }, true),
      U('Stimulans', 650, '+10% extra snelheidsbuff', { buffRate: 0.1 }),
      U('Wonderdokter', 1300, '+15% schadebuff, +5 HP per golf. ULTIMATE', { buffDmg: 0.15, heal: 5, buffRange: 0.5 }, true),
    ] },
  // ---- Rare ----
  { id: 'sluip', name: 'Sluipschutter', rarity: 'rare', role: 'Groot bereik', title: 'Mist nooit', style: 'projectile', cost: 420,
    desc: 'Enorm bereik en harde schoten, maar traag. Perfect om sterke vijanden van ver uit te schakelen.',
    base: { dmg: 70, range: 6, rate: 0.35, crit: 0.3, critMult: 2.5, air: true, projSpeed: 40 },
    look: { skin: '#c68642', suit: '#3f3f46', suit2: '#84cc16', cape: '#27272a', hair: 'cap', hairC: '#365314', goggles: true, emblem: 'eye', weapon: 'rifle' },
    fx: 'dust', proj: 'snipe', ability: 'headshot',
    upgrades: [
      U('Kaliber .50', 230, '+35 schade', { dmg: 35 }),
      U('Telescoopvizier', 380, '+1.5 bereik', { range: 1.5 }),
      U('Doorboorkogel', 700, 'Kogels doorboren 3 vijanden en breken 5 pantser', { pierce: 3, shred: 5 }, true),
      U('Snelgrendel', 950, '+0.2 snelheid, +10% crit', { rate: 0.2, crit: 0.1 }),
      U('Spookschutter', 1900, '+120 schade, +3 bereik. ULTIMATE', { dmg: 120, range: 3 }, true),
    ] },
  { id: 'wervel', name: 'Windwervel', rarity: 'rare', role: 'Area damage', title: 'Zij is de storm', style: 'aura', cost: 400,
    desc: 'Windstoten raken alles rondom haar, duwen vijanden terug en vertragen ze.',
    base: { dmg: 10, range: 2.2, rate: 1.2, knock: 0.12, slow: 0.2, slowDur: 0.8, air: true },
    look: { skin: '#f5d0a9', suit: '#0e7490', suit2: '#a5f3fc', cape: '#155e75', hair: 'long', hairC: '#cffafe', emblem: 'wind', weapon: 'none' },
    fx: 'wind', ability: 'cyclone',
    upgrades: [
      U('Rukwinden', 220, '+6 schade', { dmg: 6 }),
      U('Windhoos', 360, '+0.4 bereik, sterkere terugduw', { range: 0.4, knock: 0.08 }),
      U('Orkaanoog', 680, '+10% vertraging, +0.4 snelheid', { slow: 0.1, rate: 0.4 }, true),
      U('Straalstroom', 900, '+14 schade, breekt 2 pantser', { dmg: 14, shred: 2 }),
      U('Stormgodin', 1800, '+25 schade, groter bereik. ULTIMATE', { dmg: 25, range: 0.8 }, true),
    ] },
  // ---- Epic ----
  { id: 'flits', name: 'Flitsbliksem', rarity: 'epic', role: 'Snelle aanvallen', title: 'Sneller dan het licht', style: 'melee', cost: 600,
    desc: 'Vijf stoten per seconde en hij raakt zelfs vliegende vijanden. Zijn ability rent door hele groepen heen.',
    base: { dmg: 9, range: 1.7, rate: 5, air: true },
    look: { skin: '#f1c27d', suit: '#dc2626', suit2: '#fde047', cape: null, hair: 'spiky', hairC: '#fbbf24', mask: '#991b1b', emblem: 'bolt', weapon: 'fists' },
    fx: 'spark', ability: 'speedforce',
    upgrades: [
      U('Supersnelheid', 420, '+1.5 aanvalssnelheid', { rate: 1.5 }),
      U('Vuistenregen', 600, '+5 schade', { dmg: 5 }),
      U('Wervelvuisten', 1100, 'Stoten raken ook alles rondom het doel', { cleave: 0.8 }, true),
      U('Lichtsnelheid', 1500, '+2 snelheid, +0.5 bereik', { rate: 2, range: 0.5 }),
      U('Snelheidskracht', 2900, '+12 schade, 15% kans om te verdoven. ULTIMATE', { dmg: 12, stunChance: 0.15, stun: 0.4 }, true),
    ] },
  { id: 'banier', name: 'Kapitein Banier', rarity: 'epic', role: 'Support', title: 'Leider van het verzet', style: 'projectile', cost: 580,
    desc: 'Gooit een stuiterend schild en maakt helden in de buurt sterker. Zijn strijdkreet boost het hele team.',
    base: { dmg: 22, range: 2.8, rate: 0.9, pierce: 3, air: true, projSpeed: 13, buffRange: 2.2, buffDmg: 0.12 },
    look: { skin: '#e8c39e', suit: '#1d4ed8', suit2: '#f8fafc', cape: '#dc2626', hair: 'helmet', hairC: '#1e3a8a', emblem: 'star', weapon: 'shield' },
    fx: 'gold', proj: 'shield', ability: 'warcry',
    upgrades: [
      U('Aanvoerder', 420, 'Helden in de buurt +8% extra schade', { buffDmg: 0.08 }),
      U('Stuiterschild', 600, 'Schild raakt 2 extra vijanden, +12 schade', { pierce: 2, dmg: 12 }),
      U('Legioensvaandel', 1100, 'Buff geeft ook +15% snelheid, groter buffbereik', { buffRate: 0.15, buffRange: 0.8 }, true),
      U('Eed van Staal', 1500, '+10% schadebuff, +20 schade', { buffDmg: 0.1, dmg: 20 }),
      U('Opperbevelhebber', 2900, 'Veel groter buffbereik, +10% snelheidsbuff. ULTIMATE', { buffRange: 1.5, buffRate: 0.1, dmg: 30 }, true),
    ] },
  // ---- Legendary ----
  { id: 'draak', name: 'Drakenridder', rarity: 'legendary', role: 'Area damage', title: 'Laatste van de drakenorde', style: 'projectile', cost: 850,
    desc: 'Grote vuurbollen met brede explosies en zware brandschade. Zijn drakenadem verzengt alles in bereik.',
    base: { dmg: 60, splash: 1.2, burn: 25, range: 3.2, rate: 0.7, air: true, projSpeed: 10 },
    look: { skin: '#d6b38a', suit: '#065f46', suit2: '#f59e0b', cape: '#7f1d1d', hair: 'helmet', hairC: '#064e3b', emblem: 'wing', weapon: 'staff', orb: '#f97316', wings: true },
    fx: 'ember', proj: 'fire', ability: 'dragonbreath',
    upgrades: [
      U('Drakenschubben', 700, '+30 schade', { dmg: 30 }),
      U('Heet Bloed', 1000, '+20 brand per seconde', { burn: 20 }),
      U('Tweekoppig', 1800, '2 vuurballen tegelijk, grotere explosies', { multi: 1, splash: 0.4 }, true),
      U('Oude Woede', 2300, '+0.3 snelheid, +0.6 bereik', { rate: 0.3, range: 0.6 }),
      U('Drakenkoning', 4200, '+90 schade, +40 brand. ULTIMATE', { dmg: 90, burn: 40 }, true),
    ] },
  { id: 'mecha', name: 'Titan-Mech', rarity: 'legendary', role: 'Hoge damage', title: 'Wandelend wapenarsenaal', style: 'strike', strike: 'missile', cost: 800,
    desc: 'Vuurt salvo\'s raketten over een groot bereik. Zijn ultimate bestookt de hele map.',
    base: { dmg: 95, splash: 1.1, range: 5, rate: 0.55, multi: 2, air: true },
    look: { skin: '#b08968', suit: '#475569', suit2: '#f97316', cape: null, hair: 'visor', hairC: '#334155', emblem: 'tri', weapon: 'blaster', big: true },
    fx: 'steam', ability: 'missilestorm',
    upgrades: [
      U('Zwaardere Kernkoppen', 700, '+45 schade', { dmg: 45 }),
      U('Doelzoekers', 1000, '+1 bereik, +1 raket per salvo', { range: 1, multi: 1 }),
      U('Clusterraketten', 1800, 'Grotere explosies, breekt 4 pantser', { splash: 0.5, shred: 4 }, true),
      U('Turboladers', 2300, '+0.25 snelheid', { rate: 0.25 }),
      U('Omega-protocol', 4200, '+130 schade, +1 raket. ULTIMATE', { dmg: 130, multi: 1 }, true),
    ] },
  // ---- Mythic ----
  { id: 'engel', name: 'Seraf', rarity: 'mythic', role: 'Support', title: 'Engel van het laatste licht', style: 'beam', cost: 1150,
    desc: 'Een heilige straal, plus een sterke buff voor helden in de buurt en herstel van je basis.',
    base: { dmg: 90, beams: 1, range: 3.6, air: true, buffRange: 3, buffRate: 0.2, buffDmg: 0.15, heal: 3 },
    look: { skin: '#fde7c8', suit: '#fefce8', suit2: '#fde047', cape: '#fef9c3', hair: 'long', hairC: '#fde68a', emblem: 'wing', weapon: 'orb', orb: '#fffbeb', halo: true, wings: true },
    fx: 'star', ability: 'divinelight',
    upgrades: [
      U('Heilig Licht', 1100, '+50 schade per seconde', { dmg: 50 }),
      U('Zegening', 1500, 'Buff +10% extra snelheid en schade', { buffRate: 0.1, buffDmg: 0.1 }),
      U('Aartsengel', 2600, '+1 straal, groter buffbereik, +4 HP per golf', { beams: 1, buffRange: 1, heal: 4 }, true),
      U('Hemelkoor', 3400, '+15% snelheidsbuff, +80 schade/s', { buffRate: 0.15, dmg: 80 }),
      U('Serafijnse Glorie', 6000, 'Buff +20% schade, +2 stralen. ULTIMATE', { buffDmg: 0.2, beams: 2, dmg: 100 }, true),
    ] },
  { id: 'midas', name: 'Koning Midas', rarity: 'mythic', role: 'Geld', title: 'Alles wat hij raakt wordt goud', style: 'strike', strike: 'gold', cost: 1100,
    desc: 'Gouden inslagen, veel extra geld per golf en per kill. Zijn aanraking verandert vijanden in goud.',
    base: { dmg: 140, splash: 1, range: 3.6, rate: 0.6, air: true, bounty: 1, income: 60 },
    look: { skin: '#e0ac69', suit: '#78350f', suit2: '#fbbf24', cape: '#b45309', hair: 'crown', hairC: '#fbbf24', emblem: 'dollar', weapon: 'staff', orb: '#fde047' },
    fx: 'gold', ability: 'midastouch',
    upgrades: [
      U('Gouden Aanraking', 1100, '+70 schade', { dmg: 70 }),
      U('Schatkamer', 1500, '+120 geld per golf', { income: 120 }),
      U('Gouden Regen', 2600, '2 inslagen tegelijk, kills leveren 3× geld op', { multi: 1, bounty: 1 }, true),
      U('Koninklijk Decreet', 3400, '+0.3 snelheid, +100 schade', { rate: 0.3, dmg: 100 }),
      U('Heer van het Goud', 6000, '+250 geld per golf, +200 schade. ULTIMATE', { income: 250, dmg: 200 }, true),
    ] },
  // ---- Exotic ----
  { id: 'prisma', name: 'Prismara', rarity: 'exotic', role: 'Area damage', title: 'Het levende regenboogkristal', style: 'beam', cost: 1500, special: 'prism',
    desc: 'Drie regenboogstralen die breken naar vijanden erachter. Haar Spectrumbreuk raakt elke vijand op de map.',
    base: { dmg: 180, beams: 3, chains: 2, range: 4.5, air: true },
    look: { skin: '#e0f2fe', suit: '#0f172a', suit2: '#67e8f9', cape: '#a78bfa', hair: 'crystal', hairC: '#f0abfc', emblem: 'diamond', weapon: 'orb', orb: '#ffffff' },
    fx: 'prism', ability: 'spectrum',
    upgrades: [
      U('Refractie', 1600, 'Elke straal breekt naar 1 extra vijand', { chains: 1 }, false, true),
      U('Kleurverzadiging', 2200, '+120 schade/s, vijanden in het licht 25% trager', { dmg: 120, slow: 0.25, slowDur: 0.6 }),
      U('Prismakroon', 3600, '+2 stralen, stralen lossen 8 pantser op', { beams: 2, shred: 8 }, true, true),
      U('Lichtbreking', 4600, '+1.5 bereik, +100 schade/s', { range: 1.5, dmg: 100 }),
      U('Absoluut Spectrum', 8500, 'Executeert gewone vijanden onder 15% HP. ULTIMATE', { execute: 0.15, dmg: 200, chains: 2 }, true, true),
    ] },
  { id: 'fantoom', name: 'Spiegelfantoom', rarity: 'exotic', role: 'Snelle aanvallen', title: 'Duizend gezichten, één klinge', style: 'projectile', cost: 1450, special: 'phantom',
    desc: 'Spookklingen die in scherven splitsen. Zijn ability roept spiegelklonen op die tijdelijk meevechten.',
    base: { dmg: 90, range: 3.8, rate: 1.1, fork: 2, air: true, projSpeed: 16, crit: 0.2 },
    look: { skin: '#ddd6fe', suit: '#312e81', suit2: '#c4b5fd', cape: '#1e1b4b', hair: 'hood', hairC: '#4338ca', emblem: 'eye', weapon: 'orb', orb: '#c4b5fd' },
    fx: 'shadow', proj: 'phantom', ability: 'mirrorarmy',
    upgrades: [
      U('Spiegelscherven', 1500, 'Elke klinge splitst in 2 extra scherven', { fork: 2 }, false, true),
      U('Schimmenstap', 2100, '+0.6 snelheid, +20% crit', { rate: 0.6, crit: 0.2 }),
      U('Tweede Spiegelbeeld', 3500, 'Werpt naar 3 doelen, klonen blijven 5s langer', { multi: 2, cloneTime: 5 }, true, true),
      U('Nachtmerrieklingen', 4400, '+90 schade, crits doen 3× schade', { dmg: 90, critMult: 1 }),
      U('Oneindige Spiegel', 8200, '+2 klonen, +1 snelheid. ULTIMATE', { rate: 1, clones: 2, dmg: 100 }, true, true),
    ] },
  // ---- Ultra ----
  { id: 'omega', name: 'Omega', rarity: 'ultra', role: 'Hoge damage', title: 'Het laatste oordeel', style: 'strike', strike: 'judge', cost: 1900, special: 'cosmic',
    desc: 'Lichtzuilen treffen vijanden overal op de map en executeren zwakke vijanden. Het Oordeel treft iedereen tegelijk.',
    base: { dmg: 320, splash: 1.4, range: 99, rate: 0.5, multi: 2, air: true, execute: 0.08 },
    look: { skin: '#fef3c7', suit: '#0a0a0a', suit2: '#fde68a', cape: '#fef3c7', hair: 'visor', hairC: '#18181b', emblem: 'omega', weapon: 'staff', orb: '#fffbeb', halo: true, wings: true },
    fx: 'star', ability: 'judgement',
    upgrades: [
      U('Alziend Oog', 2500, '+160 schade', { dmg: 160 }, false, true),
      U('Eindtijd', 3200, '+1 inslag, +0.2 snelheid', { multi: 1, rate: 0.2 }),
      U('Oordeelsdag', 5500, 'Executeert gewone vijanden onder 18% HP', { execute: 0.1 }, true, true),
      U('Kosmische Weegschaal', 7000, '+400 schade, breekt 12 pantser', { dmg: 400, shred: 12 }),
      U('Alfa en Omega', 12000, '+2 inslagen, +600 schade. ULTIMATE', { multi: 2, dmg: 600 }, true, true),
    ] },
  { id: 'genesis', name: 'Genesis', rarity: 'ultra', role: 'Support', title: 'Zij die alles schiep', style: 'beam', cost: 1800, special: 'cosmic',
    desc: 'Buffs alle helden op de hele map, levert geld en HP op, en haar Oerknal spoelt de hele golf terug.',
    base: { dmg: 260, beams: 2, range: 4.5, air: true, buffRange: 99, buffRate: 0.25, buffDmg: 0.2, income: 150, heal: 5 },
    look: { skin: '#faf5ff', suit: '#fafafa', suit2: '#a78bfa', cape: '#fde68a', hair: 'flame', hairC: '#e9d5ff', emblem: 'infinity', weapon: 'orb', orb: '#ffffff', halo: true, wings: true },
    fx: 'star', ability: 'bigbang',
    upgrades: [
      U('Scheppingskracht', 2400, 'Alle helden op de map +10% extra schade', { buffDmg: 0.1 }, false, true),
      U('Levensbron', 3000, '+5 basis-HP en +150 geld per golf', { heal: 5, income: 150 }),
      U('Tweede Dag', 5200, 'Alle helden +15% snelheid, +2 stralen', { buffRate: 0.15, beams: 2 }, true, true),
      U('Sterrenwieg', 6800, '+300 schade/s, +1 bereik', { dmg: 300, range: 1 }),
      U('Nieuwe Schepping', 12000, 'Alle helden +25% schade en snelheid. ULTIMATE', { buffDmg: 0.25, buffRate: 0.25, dmg: 300 }, true, true),
    ] },
