/* =====================================================================
   HELDENWACHT — data & content
   Nieuwe helden, vijanden, maps, gacha's en events voeg je hier toe.
   ===================================================================== */
'use strict';
const TILE = 40, COLS = 24, ROWS = 15, GW = COLS * TILE, GH = ROWS * TILE;

const RARITY_ORDER = ['common', 'uncommon', 'rare', 'epic', 'legendary', 'mythic', 'exotic', 'ultra'];
const RARITIES = {
  common:    { label: 'Common',    color: '#a3acb9', dupe: 25,   lvl: 60,  cap: 4 },
  uncommon:  { label: 'Uncommon',  color: '#4ade80', dupe: 50,   lvl: 110, cap: 4 },
  rare:      { label: 'Rare',      color: '#38bdf8', dupe: 110,  lvl: 200, cap: 3 },
  epic:      { label: 'Epic',      color: '#c084fc', dupe: 240,  lvl: 340, cap: 3 },
  legendary: { label: 'Legendary', color: '#fbbf24', dupe: 500,  lvl: 560, cap: 2 },
  mythic:    { label: 'Mythic',    color: '#ff4f8b', dupe: 1000, lvl: 900, cap: 1 },
  exotic:    { label: 'Exotic',    color: '#2dd4bf', dupe: 2500, lvl: 1400, cap: 1 },
  ultra:     { label: 'Ultra',     color: '#fde68a', dupe: 6000, lvl: 2200, cap: 1 },
};
const MAX_LEVEL = 10;

/* Upgrade helper: [naam, kosten, omschrijving, stat-wijzigingen, grote upgrade?] */
const U = (name, cost, desc, mods, major = false, excl = false) => ({ name, cost, desc, mods, major, excl });

const STYLE_LABEL = { melee: 'Melee', projectile: 'Projectiel', chain: 'Kettingbliksem', aura: 'Pulsveld', splash: 'Explosief', beam: 'Straal', strike: 'Inslag' };

const HEROES = [
  { id: 'vuist', name: 'Straatvuist', rarity: 'common', title: 'Vuistvechter van de buurt', style: 'melee', cost: 120,
    desc: 'Deelt razendsnelle stoten uit aan alles wat te dichtbij komt. Kan geen vliegende vijanden raken.',
    base: { dmg: 13, range: 1.4, rate: 1.4, air: false },
    look: { skin: '#f1c27d', suit: '#e4572e', suit2: '#ffd23f', cape: null, hair: 'spiky', hairC: '#2b1a10', mask: '#1b1b2f', emblem: 'fist', weapon: 'fists' },
    fx: 'dust', ability: 'shockwave',
    upgrades: [
      U('Boksbandages', 90, '+6 schade', { dmg: 6 }),
      U('Snelle Combo', 160, '+0.5 aanvalssnelheid', { rate: 0.5 }),
      U('Grondschok', 320, 'Stoten raken ook vijanden rond het doel, +8 schade', { cleave: 0.9, dmg: 8 }, true),
      U('IJzeren Knokkels', 520, '+16 schade, breekt 3 pantser, 12% kans om te verdoven', { dmg: 16, shred: 3, stunChance: 0.12, stun: 0.5 }),
      U('Kampioen van de Straat', 1100, '+28 schade, +0.6 snelheid, meer bereik. Ontgrendelt de ULTIMATE', { dmg: 28, rate: 0.6, range: 0.4 }, true),
    ] },
  { id: 'pijl', name: 'Pijlflits', rarity: 'common', title: 'Scherpschutter van de daken', style: 'projectile', cost: 150,
    desc: 'Schiet pijlen over lange afstand en raakt ook vliegende vijanden.',
    base: { dmg: 11, range: 3.4, rate: 1.1, air: true, projSpeed: 15 },
    look: { skin: '#e0ac69', suit: '#2a9d8f', suit2: '#e9c46a', cape: '#264653', hair: 'hood', hairC: '#1d6b62', emblem: 'arrow', weapon: 'bow' },
    fx: 'leaf', proj: 'arrow', ability: 'volley',
    upgrades: [
      U('Scherpe Punten', 100, '+5 schade', { dmg: 5 }),
      U('Valkenoog', 170, '+0.8 bereik', { range: 0.8 }),
      U('Dubbele Pees', 340, 'Schiet op 2 doelen, pijlen doorboren 1 extra vijand', { multi: 1, pierce: 1 }, true),
      U('Explosieve Pijlen', 600, 'Pijlen ontploffen bij inslag, +10 schade', { splash: 0.8, dmg: 10 }),
      U('Meesterschutter', 1250, '3 doelen, 25% kritieke treffers, +0.6 snelheid. ULTIMATE', { multi: 1, crit: 0.25, rate: 0.6, dmg: 14 }, true),
    ] },
  { id: 'kogel', name: 'Kogelkid', rarity: 'common', title: 'Snelvuur-wonderkind', style: 'projectile', cost: 140,
    desc: 'Vuurt een regen van kleine kogels af. Zwak per schot, maar ongelooflijk snel.',
    base: { dmg: 5, range: 2.6, rate: 3.0, air: true, projSpeed: 19 },
    look: { skin: '#8d5524', suit: '#f59e0b', suit2: '#1f2937', cape: null, hair: 'cap', hairC: '#dc2626', emblem: 'cross', weapon: 'blaster' },
    fx: 'dust', proj: 'bullet', ability: 'barrage',
    upgrades: [
      U('Grotere Kogels', 90, '+2 schade', { dmg: 2 }),
      U('Turbotrekker', 150, '+1 aanvalssnelheid', { rate: 1 }),
      U('Dubbelloops', 300, 'Vuurt op 2 doelen tegelijk', { multi: 1 }, true),
      U('Pantserbrekers', 520, '+4 schade, breekt 2 pantser', { dmg: 4, shred: 2 }),
      U('Kogelstorm', 1050, '+1.5 snelheid, 3 doelen. ULTIMATE', { rate: 1.5, multi: 1, dmg: 4 }, true),
    ] },
  { id: 'vonk', name: 'Vonkmeid', rarity: 'uncommon', title: 'Bliksem op twee benen', style: 'chain', cost: 260,
    desc: 'Haar bliksem springt van vijand naar vijand. Sterk tegen groepen.',
    base: { dmg: 15, range: 2.8, rate: 0.9, chains: 2, air: true },
    look: { skin: '#f5d0a9', suit: '#1e3a8a', suit2: '#facc15', cape: null, hair: 'spiky', hairC: '#fde047', mask: '#facc15', emblem: 'bolt', weapon: 'orb', orb: '#fde047' },
    fx: 'spark', ability: 'overcharge',
    upgrades: [
      U('Hoogspanning', 150, '+7 schade', { dmg: 7 }),
      U('Geleiding', 260, '+1 sprong, +0.3 bereik', { chains: 1, range: 0.3 }),
      U('Kettingstorm', 480, '+2 sprongen, 15% kans om te verdoven', { chains: 2, stunChance: 0.15, stun: 0.4 }, true),
      U('Supergeleider', 750, '+0.5 snelheid, +12 schade', { rate: 0.5, dmg: 12 }),
      U('Levende Bliksem', 1500, '+3 sprongen, +25 schade, meer bereik. ULTIMATE', { chains: 3, dmg: 25, range: 0.6 }, true),
    ] },
  { id: 'ijs', name: 'IJswacht', rarity: 'uncommon', title: 'Bewaker van de eeuwige winter', style: 'aura', cost: 240,
    desc: 'Zendt ijzige pulsen uit die alle vijanden in de buurt vertragen.',
    base: { dmg: 6, range: 2.0, rate: 0.7, slow: 0.35, slowDur: 1.5, air: true },
    look: { skin: '#dbeafe', suit: '#0ea5e9', suit2: '#e0f2fe', cape: '#7dd3fc', hair: 'crystal', hairC: '#bae6fd', emblem: 'snow', weapon: 'none' },
    fx: 'frost', ability: 'blizzard',
    upgrades: [
      U('Koude Adem', 140, '+10% vertraging, +0.3 bereik', { slow: 0.1, range: 0.3 }),
      U('IJspegels', 240, '+8 schade', { dmg: 8 }),
      U('Permafrost', 460, 'Groter bereik, langere vertraging, maakt pantser bros (-2)', { range: 0.5, slowDur: 1, shred: 2 }, true),
      U('Diepvries', 700, '15% kans om te bevriezen, +0.3 snelheid', { stunChance: 0.15, stun: 0.8, rate: 0.3 }),
      U('IJskoningin', 1400, '+20 schade, +15% vertraging, groot bereik. ULTIMATE', { dmg: 20, slow: 0.15, range: 0.6 }, true),
    ] },
  { id: 'rook', name: 'Rookbom', rarity: 'uncommon', title: 'Explosievenexpert', style: 'splash', cost: 280,
    desc: 'Gooit granaten die groepen vijanden opblazen. Raakt eerst alleen grondvijanden.',
    base: { dmg: 22, range: 2.9, rate: 0.6, splash: 1.0, air: false },
    look: { skin: '#c68642', suit: '#3f6212', suit2: '#a3e635', cape: null, hair: 'helmet', hairC: '#52525b', goggles: true, emblem: 'bomb', weapon: 'grenade' },
    fx: 'smoke', proj: 'grenade', ability: 'carpet',
    upgrades: [
      U('Grotere Lading', 160, '+10 schade', { dmg: 10 }),
      U('Clusterbommen', 300, '+0.4 explosieradius', { splash: 0.4 }),
      U('Napalm', 520, 'Explosies laten vuur achter (10 schade/s)', { burn: 10 }, true),
      U('Luchtafweer', 760, 'Raakt nu ook vliegende vijanden, +0.6 bereik, +0.2 snelheid', { air: true, range: 0.6, rate: 0.2 }),
      U('Oorlogsmachine', 1500, '+40 schade, grotere explosies. ULTIMATE', { dmg: 40, splash: 0.5, rate: 0.3 }, true),
    ] },
  { id: 'staal', name: 'Staalreus', rarity: 'rare', title: 'Het wandelende fort', style: 'melee', cost: 400,
    desc: 'Enorme klappen die groepen raken en vijanden terugduwen. Geen luchtaanval.',
    base: { dmg: 52, range: 1.6, rate: 0.55, cleave: 0.8, knock: 0.25, air: false },
    look: { skin: '#d6b38a', suit: '#64748b', suit2: '#3b82f6', cape: '#1e40af', hair: 'visor', hairC: '#1e293b', emblem: 'hex', weapon: 'fists', big: true },
    fx: 'steam', ability: 'titanslam',
    upgrades: [
      U('Versterkt Pantser', 260, '+20 schade', { dmg: 20 }),
      U('Hydraulische Armen', 420, '+0.2 snelheid, sterkere terugslag', { rate: 0.2, knock: 0.2 }),
      U('Aardbeving', 700, 'Groter slaggebied, 20% kans om te verdoven', { cleave: 0.5, stunChance: 0.2, stun: 0.6 }, true),
      U('Titaanlegering', 1000, '+50 schade, breekt 4 pantser', { dmg: 50, shred: 4 }),
      U('Onverwoestbare', 2000, '+80 schade, meer bereik en snelheid. ULTIMATE', { dmg: 80, range: 0.5, rate: 0.25 }, true),
    ] },
  { id: 'schaduw', name: 'Schaduwklauw', rarity: 'rare', title: 'Ninja van de nacht', style: 'projectile', cost: 380,
    desc: 'Werpt shurikens naar meerdere doelen tegelijk, met kans op kritieke treffers.',
    base: { dmg: 11, range: 2.6, rate: 2.0, multi: 2, crit: 0.2, air: true, projSpeed: 17 },
    look: { skin: '#e8c39e', suit: '#1e1b4b', suit2: '#a78bfa', cape: '#312e81', hair: 'ninja', hairC: '#0f0d26', emblem: 'moon', weapon: 'shuriken' },
    fx: 'shadow', proj: 'shuriken', ability: 'shadowclone',
    upgrades: [
      U('Scherpe Sterren', 240, '+5 schade', { dmg: 5 }),
      U('Schaduwstap', 400, '+0.7 snelheid', { rate: 0.7 }),
      U('Vierwerp', 720, 'Werpt naar 4 doelen tegelijk', { multi: 2 }, true),
      U('Gifklingen', 950, 'Vergiftigt: 8 schade per seconde', { burn: 8 }),
      U('Meester der Schaduwen', 1900, '+25% crit, crits doen 3× schade, +14 schade. ULTIMATE', { crit: 0.25, critMult: 1, dmg: 14 }, true),
    ] },
  { id: 'zon', name: 'Zonnestraal', rarity: 'rare', title: 'Held van het middaglicht', style: 'beam', cost: 420,
    desc: 'Een doorlopende laserstraal die sterker wordt hoe langer hij op hetzelfde doel blijft.',
    base: { dmg: 28, range: 3.0, rate: 1, air: true },
    look: { skin: '#f3d2b3', suit: '#ea580c', suit2: '#fde047', cape: '#f97316', hair: 'visor', hairC: '#7c2d12', emblem: 'sun', weapon: 'orb', orb: '#fde047' },
    fx: 'ember', ability: 'solarflare',
    upgrades: [
      U('Focuslens', 260, '+12 schade per seconde', { dmg: 12 }),
      U('Brandpunt', 400, '+0.6 bereik', { range: 0.6 }),
      U('Prisma', 760, 'Splitst de straal: raakt 2 doelen', { beams: 1 }, true),
      U('Zonnevlam', 1000, 'De straal zet vijanden in brand (12/s)', { burn: 12 }),
      U('Zonnegod', 2100, '+45 schade/s, 3 stralen, meer bereik. ULTIMATE', { dmg: 45, beams: 1, range: 0.5 }, true),
    ] },
  { id: 'storm', name: 'Stormheer', rarity: 'epic', title: 'Meester van het onweer', style: 'strike', strike: 'bolt', cost: 580,
    desc: 'Roept bliksem uit de hemel op, met explosieve inslagen en kans op verdoven.',
    base: { dmg: 42, splash: 0.9, range: 3.6, rate: 0.7, air: true, stunChance: 0.1, stun: 0.4 },
    look: { skin: '#c9a27e', suit: '#4338ca', suit2: '#e0e7ff', cape: '#312e81', hair: 'long', hairC: '#f8fafc', emblem: 'bolt', weapon: 'staff', orb: '#a5b4fc' },
    fx: 'spark', ability: 'thunderstorm',
    upgrades: [
      U('Donderslag', 400, '+20 schade', { dmg: 20 }),
      U('Onweersfront', 600, '+0.3 snelheid', { rate: 0.3 }),
      U('Supercel', 1100, 'Slaat 2 doelen tegelijk, grotere inslag', { multi: 1, splash: 0.4 }, true),
      U('Oog van de Storm', 1400, '+0.8 bereik, +15% verdoofkans', { range: 0.8, stunChance: 0.15 }),
      U('Hemelheerser', 2800, '+70 schade, 3 inslagen tegelijk. ULTIMATE', { dmg: 70, multi: 1 }, true),
    ] },
  { id: 'feniks', name: 'Vlamfeniks', rarity: 'epic', title: 'Herrezen uit de as', style: 'projectile', cost: 600,
    desc: 'Vuurballen die ontploffen en vijanden laten branden.',
    base: { dmg: 20, splash: 0.7, burn: 14, range: 3.0, rate: 1.2, air: true, projSpeed: 11 },
    look: { skin: '#f1c27d', suit: '#b91c1c', suit2: '#fbbf24', cape: '#f59e0b', hair: 'flame', hairC: '#f97316', emblem: 'flame', weapon: 'orb', orb: '#fb923c', wings: true },
    fx: 'ember', proj: 'fire', ability: 'phoenixdive',
    upgrades: [
      U('Heet Vuur', 420, '+8 brandschade per seconde', { burn: 8 }),
      U('Vuurstoot', 620, '+0.4 snelheid', { rate: 0.4 }),
      U('Vuurvleugels', 1100, '2 vuurballen tegelijk, grotere explosies', { multi: 1, splash: 0.5 }, true),
      U('Zonnekern', 1500, '+25 schade, +0.5 bereik', { dmg: 25, range: 0.5 }),
      U('Wedergeboorte', 2900, '+40 schade en +30 brand. ULTIMATE', { dmg: 40, burn: 30 }, true),
    ] },
  { id: 'grav', name: 'Gravitas', rarity: 'epic', title: 'Heer van de zwaartekracht', style: 'aura', cost: 620,
    desc: 'Zwaartekrachtpulsen die vijanden vertragen en hun pantser verpletteren.',
    base: { dmg: 18, range: 2.4, rate: 1.0, slow: 0.4, slowDur: 1, shred: 3, air: true },
    look: { skin: '#b08968', suit: '#0f172a', suit2: '#22d3ee', cape: '#0e7490', hair: 'helmet', hairC: '#334155', emblem: 'ring', weapon: 'orb', orb: '#22d3ee' },
    fx: 'void', ability: 'singularity',
    upgrades: [
      U('Zwaartekrachtveld', 450, '+10 schade, +0.3 bereik', { dmg: 10, range: 0.3 }),
      U('Verpletterend', 650, 'Breekt 3 extra pantser', { shred: 3 }),
      U('Waarnemingshorizon', 1200, '20% kans om te verdoven, sterkere vertraging', { stunChance: 0.2, stun: 0.5, slow: 0.1 }, true),
      U('Massaversneller', 1600, '+0.4 snelheid, +20 schade', { rate: 0.4, dmg: 20 }),
      U('Zwart Gat', 3000, '+50 schade, groot bereik. ULTIMATE', { dmg: 50, range: 0.7 }, true),
    ] },
  { id: 'kosmos', name: 'Kosmoskapitein', rarity: 'legendary', title: 'Bevelhebber van de baan', style: 'strike', strike: 'laser', cost: 820,
    desc: 'Stuurt satellietlasers naar vijanden over een enorm bereik.',
    base: { dmg: 110, splash: 1.2, range: 4.5, rate: 0.45, air: true },
    look: { skin: '#e8c39e', suit: '#0b1026', suit2: '#f8fafc', cape: '#1d4ed8', hair: 'dome', hairC: '#cbd5e1', emblem: 'star', weapon: 'orb', orb: '#93c5fd' },
    fx: 'star', ability: 'orbitalcannon',
    upgrades: [
      U('Satellietlink', 700, '+50 schade', { dmg: 50 }),
      U('Snelladers', 1000, '+0.2 snelheid', { rate: 0.2 }),
      U('Tweelingsatelliet', 1800, 'Vuurt op 2 doelen, grotere inslag', { multi: 1, splash: 0.4 }, true),
      U('Zwaartekrachtbom', 2300, 'Inslagen breken 5 pantser en vertragen 30%', { shred: 5, slow: 0.3, slowDur: 1.5 }),
      U('Admiraal der Sterren', 4200, '+150 schade, +1 bereik. ULTIMATE', { dmg: 150, range: 1 }, true),
    ] },
  { id: 'tijd', name: 'Tijdwever', rarity: 'legendary', title: 'Hoeder van het uur', style: 'projectile', cost: 780,
    desc: 'Tijdschichten die vijanden sterk vertragen. Kan de tijd terugdraaien.',
    base: { dmg: 38, range: 3.4, rate: 1.0, slow: 0.5, slowDur: 2, air: true, projSpeed: 13 },
    look: { skin: '#f5d0a9', suit: '#115e59', suit2: '#fcd34d', cape: '#0f766e', hair: 'hood', hairC: '#134e4a', emblem: 'clock', weapon: 'staff', orb: '#fcd34d' },
    fx: 'gold', proj: 'time', ability: 'timerewind',
    upgrades: [
      U('Zandloper', 650, '+20 schade', { dmg: 20 }),
      U('Tijdvertraging', 950, 'Vertraging duurt 1s langer en is 10% sterker', { slowDur: 1, slow: 0.1 }),
      U('Paradox', 1700, 'Schiet op 2 doelen, doorboort 2 vijanden', { multi: 1, pierce: 2 }, true),
      U('Chronosplijter', 2200, '+0.5 snelheid, 10% kans op tijdstop', { rate: 0.5, stunChance: 0.1, stun: 1 }),
      U('Heer van de Tijd', 4000, '+70 schade, 3 doelen. ULTIMATE', { dmg: 70, multi: 1 }, true),
    ] },
  { id: 'nova', name: 'Nova Prime', rarity: 'mythic', title: 'Geboren uit een ster', style: 'beam', cost: 1150,
    desc: 'Twee verzengende sterrenstralen tegelijk. Haar supernova raakt de hele map.',
    base: { dmg: 120, beams: 2, range: 4.0, burn: 20, air: true },
    look: { skin: '#fde7c8', suit: '#fef3c7', suit2: '#f59e0b', cape: '#fbbf24', hair: 'flame', hairC: '#fff7ed', emblem: 'diamond', weapon: 'orb', orb: '#ffffff', halo: true },
    fx: 'star', ability: 'supernova',
    upgrades: [
      U('Stellaire Kern', 1100, '+60 schade per seconde', { dmg: 60 }),
      U('Zonnewind', 1500, '+0.6 bereik', { range: 0.6 }),
      U('Tweelingster', 2600, '+1 straal (3 doelen)', { beams: 1 }, true),
      U('Kernfusie', 3400, '+40 brand, breekt 6 pantser', { burn: 40, shred: 6 }),
      U('Oerster', 6000, '+200 schade/s, +1 straal. ULTIMATE', { dmg: 200, beams: 1, range: 0.5 }, true),
    ] },
  { id: 'leegte', name: 'Leegtekoning', rarity: 'mythic', title: 'Heerser van het niets', style: 'projectile', cost: 1200,
    desc: 'Leegtebollen die pantser oplossen en alles in de buurt verscheuren. Opent zwarte gaten.',
    base: { dmg: 170, splash: 1.3, range: 4.0, rate: 0.8, shred: 6, air: true, projSpeed: 9 },
    look: { skin: '#c4b5fd', suit: '#1a0b2e', suit2: '#d946ef', cape: '#4c1d95', hair: 'crown', hairC: '#a21caf', emblem: 'void', weapon: 'orb', orb: '#d946ef' },
    fx: 'void', proj: 'void', ability: 'eventhorizon',
    upgrades: [
      U('Duistere Materie', 1200, '+80 schade', { dmg: 80 }),
      U('Leegte-echo', 1600, '+0.3 snelheid, +0.3 explosieradius', { rate: 0.3, splash: 0.3 }),
      U('Tweelingmanen', 2800, '2 leegtebollen tegelijk', { multi: 1 }, true),
      U('Entropie', 3600, 'Vertraagt 40% en verbrandt 50/s', { slow: 0.4, slowDur: 1.5, burn: 50 }),
      U('Koning van Niets', 6500, '+250 schade, groot bereik. ULTIMATE', { dmg: 250, range: 0.8, rate: 0.2 }, true),
    ] },

  /* ================= Uitbreiding: nieuwe helden ================= */
  // ---- Uncommon ----
  { id: 'munt', name: 'Muntmagnaat', rarity: 'uncommon', role: 'Geld', cap: 2, title: 'Miljonair met een missie', style: 'projectile', cost: 220,
    desc: 'Schiet gouden munten en levert elke golf extra geld op. Kills van hem geven een bonus.',
    base: { dmg: 8, range: 2.6, rate: 1.2, air: true, projSpeed: 14, income: 20, bounty: 0.3 },
    look: { skin: '#f1c27d', suit: '#15803d', suit2: '#facc15', cape: '#166534', hair: 'cap', hairC: '#facc15', emblem: 'dollar', weapon: 'orb', orb: '#facc15' },
    fx: 'gold', proj: 'coin', ability: 'goldrush',
    upgrades: [
      U('Spaarpot', 120, '+15 geld per golf', { income: 15 }),
      U('Premiejager', 200, 'Kills leveren 30% extra geld op, +4 schade', { bounty: 0.3, dmg: 4 }),
      U('Gouden Kluis', 400, '+30 geld per golf, munten doorboren 1 vijand', { income: 30, pierce: 1 }, true),
      U('Rente op Rente', 600, '+25 geld per golf, +0.4 snelheid', { income: 25, rate: 0.4 }),
      U('Beursgoeroe', 1200, '+60 geld per golf, kills +50% geld. ULTIMATE', { income: 60, bounty: 0.5, dmg: 10 }, true),
    ] },
  { id: 'medic', name: 'Veldarts', rarity: 'uncommon', role: 'Support', title: 'Houdt het team op de been', style: 'projectile', cost: 230,
    desc: 'Maakt helden in de buurt sneller en herstelt na elke golf wat basis-HP.',
    base: { dmg: 7, range: 2.4, rate: 1, air: true, projSpeed: 14, buffRange: 2, buffRate: 0.12, heal: 2 },
    look: { skin: '#e0ac69', suit: '#f8fafc', suit2: '#ef4444', cape: null, hair: 'long', hairC: '#78350f', emblem: 'cross', weapon: 'orb', orb: '#fca5a5' },
    fx: 'star', proj: 'bullet', ability: 'rally',
    upgrades: [
      U('Adrenaline', 130, 'Helden in de buurt +8% extra aanvalssnelheid', { buffRate: 0.08 }),
      U('Verbandtas', 220, 'Herstelt 3 extra basis-HP per golf', { heal: 3 }),
      U('Veldhospitaal', 420, 'Groter buffbereik, helden in de buurt +10% schade', { buffRange: 0.8, buffDmg: 0.1 }, true),
      U('Stimulans', 650, '+10% extra snelheidsbuff', { buffRate: 0.1 }),
      U('Wonderdokter', 1300, '+15% schadebuff, +5 HP per golf. ULTIMATE', { buffDmg: 0.15, heal: 5, buffRange: 0.5 }, true),
    ] },
  // ---- Rare ----
  { id: 'sluip', name: 'Sluipschutter', rarity: 'rare', role: 'Groot bereik', title: 'Mist nooit', style: 'projectile', cost: 420,
    desc: 'Enorm bereik en harde schoten, maar traag. Perfect om sterke vijanden van ver uit te schakelen.',
    base: { dmg: 70, range: 6, rate: 0.35, crit: 0.3, critMult: 2.5, air: true, projSpeed: 40 },
    look: { skin: '#c68642', suit: '#3f3f46', suit2: '#84cc16', cape: '#27272a', hair: 'cap', hairC: '#365314', goggles: true, emblem: 'eye', weapon: 'rifle' },
    fx: 'dust', proj: 'snipe', ability: 'headshot',
    upgrades: [
      U('Kaliber .50', 230, '+35 schade', { dmg: 35 }),
      U('Telescoopvizier', 380, '+1.5 bereik', { range: 1.5 }),
      U('Doorboorkogel', 700, 'Kogels doorboren 3 vijanden en breken 5 pantser', { pierce: 3, shred: 5 }, true),
      U('Snelgrendel', 950, '+0.2 snelheid, +10% crit', { rate: 0.2, crit: 0.1 }),
      U('Spookschutter', 1900, '+120 schade, +3 bereik. ULTIMATE', { dmg: 120, range: 3 }, true),
    ] },
  { id: 'wervel', name: 'Windwervel', rarity: 'rare', role: 'Area damage', title: 'Zij is de storm', style: 'aura', cost: 400,
    desc: 'Windstoten raken alles rondom haar, duwen vijanden terug en vertragen ze.',
    base: { dmg: 10, range: 2.2, rate: 1.2, knock: 0.12, slow: 0.2, slowDur: 0.8, air: true },
    look: { skin: '#f5d0a9', suit: '#0e7490', suit2: '#a5f3fc', cape: '#155e75', hair: 'long', hairC: '#cffafe', emblem: 'wind', weapon: 'none' },
    fx: 'wind', ability: 'cyclone',
    upgrades: [
      U('Rukwinden', 220, '+6 schade', { dmg: 6 }),
      U('Windhoos', 360, '+0.4 bereik, sterkere terugduw', { range: 0.4, knock: 0.08 }),
      U('Orkaanoog', 680, '+10% vertraging, +0.4 snelheid', { slow: 0.1, rate: 0.4 }, true),
      U('Straalstroom', 900, '+14 schade, breekt 2 pantser', { dmg: 14, shred: 2 }),
      U('Stormgodin', 1800, '+25 schade, groter bereik. ULTIMATE', { dmg: 25, range: 0.8 }, true),
    ] },
  // ---- Epic ----
  { id: 'flits', name: 'Flitsbliksem', rarity: 'epic', role: 'Snelle aanvallen', title: 'Sneller dan het licht', style: 'melee', cost: 600,
    desc: 'Vijf stoten per seconde en hij raakt zelfs vliegende vijanden. Zijn ability rent door hele groepen heen.',
    base: { dmg: 9, range: 1.7, rate: 5, air: true },
    look: { skin: '#f1c27d', suit: '#dc2626', suit2: '#fde047', cape: null, hair: 'spiky', hairC: '#fbbf24', mask: '#991b1b', emblem: 'bolt', weapon: 'fists' },
    fx: 'spark', ability: 'speedforce',
    upgrades: [
      U('Supersnelheid', 420, '+1.5 aanvalssnelheid', { rate: 1.5 }),
      U('Vuistenregen', 600, '+5 schade', { dmg: 5 }),
      U('Wervelvuisten', 1100, 'Stoten raken ook alles rondom het doel', { cleave: 0.8 }, true),
      U('Lichtsnelheid', 1500, '+2 snelheid, +0.5 bereik', { rate: 2, range: 0.5 }),
      U('Snelheidskracht', 2900, '+12 schade, 15% kans om te verdoven. ULTIMATE', { dmg: 12, stunChance: 0.15, stun: 0.4 }, true),
    ] },
  { id: 'banier', name: 'Kapitein Banier', rarity: 'epic', role: 'Support', title: 'Leider van het verzet', style: 'projectile', cost: 580,
    desc: 'Gooit een stuiterend schild en maakt helden in de buurt sterker. Zijn strijdkreet boost het hele team.',
    base: { dmg: 22, range: 2.8, rate: 0.9, pierce: 3, air: true, projSpeed: 13, buffRange: 2.2, buffDmg: 0.12 },
    look: { skin: '#e8c39e', suit: '#1d4ed8', suit2: '#f8fafc', cape: '#dc2626', hair: 'helmet', hairC: '#1e3a8a', emblem: 'star', weapon: 'shield' },
    fx: 'gold', proj: 'shield', ability: 'warcry',
    upgrades: [
      U('Aanvoerder', 420, 'Helden in de buurt +8% extra schade', { buffDmg: 0.08 }),
      U('Stuiterschild', 600, 'Schild raakt 2 extra vijanden, +12 schade', { pierce: 2, dmg: 12 }),
      U('Legioensvaandel', 1100, 'Buff geeft ook +15% snelheid, groter buffbereik', { buffRate: 0.15, buffRange: 0.8 }, true),
      U('Eed van Staal', 1500, '+10% schadebuff, +20 schade', { buffDmg: 0.1, dmg: 20 }),
      U('Opperbevelhebber', 2900, 'Veel groter buffbereik, +10% snelheidsbuff. ULTIMATE', { buffRange: 1.5, buffRate: 0.1, dmg: 30 }, true),
    ] },
  // ---- Legendary ----
  { id: 'draak', name: 'Drakenridder', rarity: 'legendary', role: 'Area damage', title: 'Laatste van de drakenorde', style: 'projectile', cost: 850,
    desc: 'Grote vuurbollen met brede explosies en zware brandschade. Zijn drakenadem verzengt alles in bereik.',
    base: { dmg: 60, splash: 1.2, burn: 25, range: 3.2, rate: 0.7, air: true, projSpeed: 10 },
    look: { skin: '#d6b38a', suit: '#065f46', suit2: '#f59e0b', cape: '#7f1d1d', hair: 'helmet', hairC: '#064e3b', emblem: 'wing', weapon: 'staff', orb: '#f97316', wings: true },
    fx: 'ember', proj: 'fire', ability: 'dragonbreath',
    upgrades: [
      U('Drakenschubben', 700, '+30 schade', { dmg: 30 }),
      U('Heet Bloed', 1000, '+20 brand per seconde', { burn: 20 }),
      U('Tweekoppig', 1800, '2 vuurballen tegelijk, grotere explosies', { multi: 1, splash: 0.4 }, true),
      U('Oude Woede', 2300, '+0.3 snelheid, +0.6 bereik', { rate: 0.3, range: 0.6 }),
      U('Drakenkoning', 4200, '+90 schade, +40 brand. ULTIMATE', { dmg: 90, burn: 40 }, true),
    ] },
  { id: 'mecha', name: 'Titan-Mech', rarity: 'legendary', role: 'Hoge damage', title: 'Wandelend wapenarsenaal', style: 'strike', strike: 'missile', cost: 800,
    desc: 'Vuurt salvo\'s raketten over een groot bereik. Zijn ultimate bestookt de hele map.',
    base: { dmg: 95, splash: 1.1, range: 5, rate: 0.55, multi: 2, air: true },
    look: { skin: '#b08968', suit: '#475569', suit2: '#f97316', cape: null, hair: 'visor', hairC: '#334155', emblem: 'tri', weapon: 'blaster', big: true },
    fx: 'steam', ability: 'missilestorm',
    upgrades: [
      U('Zwaardere Kernkoppen', 700, '+45 schade', { dmg: 45 }),
      U('Doelzoekers', 1000, '+1 bereik, +1 raket per salvo', { range: 1, multi: 1 }),
      U('Clusterraketten', 1800, 'Grotere explosies, breekt 4 pantser', { splash: 0.5, shred: 4 }, true),
      U('Turboladers', 2300, '+0.25 snelheid', { rate: 0.25 }),
      U('Omega-protocol', 4200, '+130 schade, +1 raket. ULTIMATE', { dmg: 130, multi: 1 }, true),
    ] },
  // ---- Mythic ----
  { id: 'engel', name: 'Seraf', rarity: 'mythic', role: 'Support', title: 'Engel van het laatste licht', style: 'beam', cost: 1150,
    desc: 'Een heilige straal, plus een sterke buff voor helden in de buurt en herstel van je basis.',
    base: { dmg: 90, beams: 1, range: 3.6, air: true, buffRange: 3, buffRate: 0.2, buffDmg: 0.15, heal: 3 },
    look: { skin: '#fde7c8', suit: '#fefce8', suit2: '#fde047', cape: '#fef9c3', hair: 'long', hairC: '#fde68a', emblem: 'wing', weapon: 'orb', orb: '#fffbeb', halo: true, wings: true },
    fx: 'star', ability: 'divinelight',
    upgrades: [
      U('Heilig Licht', 1100, '+50 schade per seconde', { dmg: 50 }),
      U('Zegening', 1500, 'Buff +10% extra snelheid en schade', { buffRate: 0.1, buffDmg: 0.1 }),
      U('Aartsengel', 2600, '+1 straal, groter buffbereik, +4 HP per golf', { beams: 1, buffRange: 1, heal: 4 }, true),
      U('Hemelkoor', 3400, '+15% snelheidsbuff, +80 schade/s', { buffRate: 0.15, dmg: 80 }),
      U('Serafijnse Glorie', 6000, 'Buff +20% schade, +2 stralen. ULTIMATE', { buffDmg: 0.2, beams: 2, dmg: 100 }, true),
    ] },
  { id: 'midas', name: 'Koning Midas', rarity: 'mythic', role: 'Geld', title: 'Alles wat hij raakt wordt goud', style: 'strike', strike: 'gold', cost: 1100,
    desc: 'Gouden inslagen, veel extra geld per golf en per kill. Zijn aanraking verandert vijanden in goud.',
    base: { dmg: 140, splash: 1, range: 3.6, rate: 0.6, air: true, bounty: 1, income: 60 },
    look: { skin: '#e0ac69', suit: '#78350f', suit2: '#fbbf24', cape: '#b45309', hair: 'crown', hairC: '#fbbf24', emblem: 'dollar', weapon: 'staff', orb: '#fde047' },
    fx: 'gold', ability: 'midastouch',
    upgrades: [
      U('Gouden Aanraking', 1100, '+70 schade', { dmg: 70 }),
      U('Schatkamer', 1500, '+120 geld per golf', { income: 120 }),
      U('Gouden Regen', 2600, '2 inslagen tegelijk, kills leveren 3× geld op', { multi: 1, bounty: 1 }, true),
      U('Koninklijk Decreet', 3400, '+0.3 snelheid, +100 schade', { rate: 0.3, dmg: 100 }),
      U('Heer van het Goud', 6000, '+250 geld per golf, +200 schade. ULTIMATE', { income: 250, dmg: 200 }, true),
    ] },
  // ---- Exotic ----
  { id: 'prisma', name: 'Prismara', rarity: 'exotic', role: 'Area damage', title: 'Het levende regenboogkristal', style: 'beam', cost: 1500, special: 'prism',
    desc: 'Drie regenboogstralen die breken naar vijanden erachter. Haar Spectrumbreuk raakt elke vijand op de map.',
    base: { dmg: 180, beams: 3, chains: 2, range: 4.5, air: true },
    look: { skin: '#e0f2fe', suit: '#0f172a', suit2: '#67e8f9', cape: '#a78bfa', hair: 'crystal', hairC: '#f0abfc', emblem: 'diamond', weapon: 'orb', orb: '#ffffff' },
    fx: 'prism', ability: 'spectrum',
    upgrades: [
      U('Refractie', 1600, 'Elke straal breekt naar 1 extra vijand', { chains: 1 }, false, true),
      U('Kleurverzadiging', 2200, '+120 schade/s, vijanden in het licht 25% trager', { dmg: 120, slow: 0.25, slowDur: 0.6 }),
      U('Prismakroon', 3600, '+2 stralen, stralen lossen 8 pantser op', { beams: 2, shred: 8 }, true, true),
      U('Lichtbreking', 4600, '+1.5 bereik, +100 schade/s', { range: 1.5, dmg: 100 }),
      U('Absoluut Spectrum', 8500, 'Executeert gewone vijanden onder 15% HP. ULTIMATE', { execute: 0.15, dmg: 200, chains: 2 }, true, true),
    ] },
  { id: 'fantoom', name: 'Spiegelfantoom', rarity: 'exotic', role: 'Snelle aanvallen', title: 'Duizend gezichten, één klinge', style: 'projectile', cost: 1450, special: 'phantom',
    desc: 'Spookklingen die in scherven splitsen. Zijn ability roept spiegelklonen op die tijdelijk meevechten.',
    base: { dmg: 90, range: 3.8, rate: 1.1, fork: 2, air: true, projSpeed: 16, crit: 0.2 },
    look: { skin: '#ddd6fe', suit: '#312e81', suit2: '#c4b5fd', cape: '#1e1b4b', hair: 'hood', hairC: '#4338ca', emblem: 'eye', weapon: 'orb', orb: '#c4b5fd' },
    fx: 'shadow', proj: 'phantom', ability: 'mirrorarmy',
    upgrades: [
      U('Spiegelscherven', 1500, 'Elke klinge splitst in 2 extra scherven', { fork: 2 }, false, true),
      U('Schimmenstap', 2100, '+0.6 snelheid, +20% crit', { rate: 0.6, crit: 0.2 }),
      U('Tweede Spiegelbeeld', 3500, 'Werpt naar 3 doelen, klonen blijven 5s langer', { multi: 2, cloneTime: 5 }, true, true),
      U('Nachtmerrieklingen', 4400, '+90 schade, crits doen 3× schade', { dmg: 90, critMult: 1 }),
      U('Oneindige Spiegel', 8200, '+2 klonen, +1 snelheid. ULTIMATE', { rate: 1, clones: 2, dmg: 100 }, true, true),
    ] },
  // ---- Ultra ----
  { id: 'omega', name: 'Omega', rarity: 'ultra', role: 'Hoge damage', title: 'Het laatste oordeel', style: 'strike', strike: 'judge', cost: 1900, special: 'cosmic',
    desc: 'Lichtzuilen treffen vijanden overal op de map en executeren zwakke vijanden. Het Oordeel treft iedereen tegelijk.',
    base: { dmg: 320, splash: 1.4, range: 99, rate: 0.5, multi: 2, air: true, execute: 0.08 },
    look: { skin: '#fef3c7', suit: '#0a0a0a', suit2: '#fde68a', cape: '#fef3c7', hair: 'visor', hairC: '#18181b', emblem: 'omega', weapon: 'staff', orb: '#fffbeb', halo: true, wings: true },
    fx: 'star', ability: 'judgement',
    upgrades: [
      U('Alziend Oog', 2500, '+160 schade', { dmg: 160 }, false, true),
      U('Eindtijd', 3200, '+1 inslag, +0.2 snelheid', { multi: 1, rate: 0.2 }),
      U('Oordeelsdag', 5500, 'Executeert gewone vijanden onder 18% HP', { execute: 0.1 }, true, true),
      U('Kosmische Weegschaal', 7000, '+400 schade, breekt 12 pantser', { dmg: 400, shred: 12 }),
      U('Alfa en Omega', 12000, '+2 inslagen, +600 schade. ULTIMATE', { multi: 2, dmg: 600 }, true, true),
    ] },
  { id: 'genesis', name: 'Genesis', rarity: 'ultra', role: 'Support', title: 'Zij die alles schiep', style: 'beam', cost: 1800, special: 'cosmic',
    desc: 'Buffs alle helden op de hele map, levert geld en HP op, en haar Oerknal spoelt de hele golf terug.',
    base: { dmg: 260, beams: 2, range: 4.5, air: true, buffRange: 99, buffRate: 0.25, buffDmg: 0.2, income: 150, heal: 5 },
    look: { skin: '#faf5ff', suit: '#fafafa', suit2: '#a78bfa', cape: '#fde68a', hair: 'flame', hairC: '#e9d5ff', emblem: 'infinity', weapon: 'orb', orb: '#ffffff', halo: true, wings: true },
    fx: 'star', ability: 'bigbang',
    upgrades: [
      U('Scheppingskracht', 2400, 'Alle helden op de map +10% extra schade', { buffDmg: 0.1 }, false, true),
      U('Levensbron', 3000, '+5 basis-HP en +150 geld per golf', { heal: 5, income: 150 }),
      U('Tweede Dag', 5200, 'Alle helden +15% snelheid, +2 stralen', { buffRate: 0.15, beams: 2 }, true, true),
      U('Sterrenwieg', 6800, '+300 schade/s, +1 bereik', { dmg: 300, range: 1 }),
      U('Nieuwe Schepping', 12000, 'Alle helden +25% schade en snelheid. ULTIMATE', { buffDmg: 0.25, buffRate: 0.25, dmg: 300 }, true, true),
    ] },

  /* ================= Sterke starters (goedkoop, sterk in het begin) =================
     earlyBoost: extra schade die van golf 1 tot golf 15 afneemt naar 0. Upgrades zijn bewust bescheiden. */
  { id: 'tweeling', name: 'Turbotweeling', rarity: 'epic', role: 'Starter', title: 'Twee blasters, nul geduld', style: 'projectile', cost: 290,
    desc: 'Goedkope epic met twee plasmablasters die op 2 doelen tegelijk vuren. Heel sterk in de eerste golven; tegen zwaar pantser later minder.',
    base: { dmg: 8, range: 2.8, rate: 2.6, multi: 2, air: true, projSpeed: 18, earlyBoost: 0.7 },
    look: { skin: '#f1c27d', suit: '#0891b2', suit2: '#f472b6', cape: null, hair: 'spiky', hairC: '#f472b6', mask: '#164e63', emblem: 'arrow', weapon: 'blaster' },
    fx: 'spark', proj: 'plasma', ability: 'twinstorm',
    upgrades: [
      U('Gekoelde Lopen', 150, '+3 schade', { dmg: 3 }),
      U('Snelvuurmodus', 250, '+0.4 aanvalssnelheid', { rate: 0.4 }),
      U('Derde Loop', 450, 'Vuurt op 3 doelen tegelijk', { multi: 1 }, true),
      U('Plasmakern', 550, '+3 schade, +0.3 bereik', { dmg: 3, range: 0.3 }),
      U('Tweelingstorm', 900, '+4 schade, +0.5 snelheid. ULTIMATE', { dmg: 4, rate: 0.5 }, true),
    ] },
  { id: 'schildmaagd', name: 'Schildmaagd', rarity: 'legendary', role: 'Starter', title: 'Eerste linie van de stad', style: 'melee', cost: 340,
    desc: 'Goedkope legendary die met haar schild groepen raakt en terugduwt. Haar ability zet een muur op het pad die vijanden tegenhoudt.',
    base: { dmg: 30, range: 1.7, rate: 1.1, cleave: 0.9, knock: 0.1, air: false, earlyBoost: 0.7 },
    look: { skin: '#e0ac69', suit: '#9f1239', suit2: '#fbbf24', cape: '#fbbf24', hair: 'long', hairC: '#fef3c7', emblem: 'hex', weapon: 'shield' },
    fx: 'gold', ability: 'bulwark',
    upgrades: [
      U('Scherpe Rand', 180, '+10 schade', { dmg: 10 }),
      U('Snelle Slagen', 300, '+0.25 snelheid, +0.2 bereik', { rate: 0.25, range: 0.2 }),
      U('Schildwal', 500, 'Groter slaggebied, sterkere terugduw', { cleave: 0.4, knock: 0.08 }, true),
      U('Gewijd Staal', 650, '+12 schade, breekt 2 pantser', { dmg: 12, shred: 2 }),
      U('Onwrikbaar', 1000, '+15 schade, 10% kans om te verdoven. ULTIMATE', { dmg: 15, stunChance: 0.1, stun: 0.5 }, true),
    ] },
  { id: 'sterrenkind', name: 'Sterrenkind', rarity: 'mythic', role: 'Starter', title: 'Viel vorige week uit de hemel', style: 'projectile', cost: 380,
    desc: 'Goedkope mythic die stuiterende sterren gooit met kleine explosies en luchtaanval. Haar wensster levert ook geld op.',
    base: { dmg: 20, range: 3.2, rate: 1.5, splash: 0.6, pierce: 2, air: true, projSpeed: 14, earlyBoost: 0.8 },
    look: { skin: '#fde7c8', suit: '#1e1b4b', suit2: '#fde68a', cape: '#6366f1', hair: 'spiky', hairC: '#c7d2fe', emblem: 'star', weapon: 'orb', orb: '#fde68a', halo: true },
    fx: 'star', proj: 'star', ability: 'wishingstar',
    upgrades: [
      U('Vallende Ster', 200, '+7 schade', { dmg: 7 }),
      U('Sterrenstof', 320, '+0.3 snelheid, +0.3 bereik', { rate: 0.3, range: 0.3 }),
      U('Sterrenbeeld', 550, 'Sterren stuiteren door 1 extra vijand, grotere explosie', { pierce: 1, splash: 0.2 }, true),
      U('Maanlicht', 700, '+10 schade', { dmg: 10 }),
      U('Kleine Supernova', 1100, '+16 schade, +0.2 snelheid. ULTIMATE', { dmg: 16, rate: 0.2 }, true),
    ] },
];
const HERO = Object.fromEntries(HEROES.map(h => [h.id, h]));
/* Speelstijl per held (nieuwe helden hebben 'role' in hun eigen definitie) */
const ROLE_DEFAULT = { vuist: 'Snelle aanvallen', pijl: 'Groot bereik', kogel: 'Snelle aanvallen', vonk: 'Area damage', ijs: 'Controle', rook: 'Area damage', staal: 'Hoge damage', schaduw: 'Snelle aanvallen', zon: 'Hoge damage', storm: 'Area damage', feniks: 'Area damage', grav: 'Controle', kosmos: 'Groot bereik', tijd: 'Controle', nova: 'Hoge damage', leegte: 'Area damage' };
HEROES.forEach(h => { if (!h.role) h.role = ROLE_DEFAULT[h.id] || 'Allround'; });

/* Abilities: naam, ultimate-naam, cooldown, omschrijving. Logica staat in de engine (ABILITY_FX). */
const ABILITIES = {
  shockwave:     { name: 'Schokgolf',       ult: 'Kampioensklap',      cd: 18, desc: 'Slaat op de grond: schade en verdoving rondom.' },
  volley:        { name: 'Pijlenregen',     ult: 'Hemel vol Pijlen',   cd: 20, desc: 'Laat een regen van pijlen op vijanden in bereik neerdalen.' },
  barrage:       { name: 'Kogelregen',      ult: 'Lood-orkaan',        cd: 18, desc: '4 seconden lang 3× zo snel schieten op extra doelen.' },
  overcharge:    { name: 'Overbelasting',   ult: 'Gigawatt',           cd: 22, desc: 'Dubbele snelheid en +3 sprongen voor 6 seconden.' },
  blizzard:      { name: 'Sneeuwstorm',     ult: 'Eeuwige Winter',     cd: 24, desc: 'Bevriest alle vijanden in bereik.' },
  carpet:        { name: 'Bommentapijt',    ult: 'Totale Vernietiging', cd: 25, desc: 'Een reeks explosies langs het pad.' },
  titanslam:     { name: 'Titanenklap',     ult: 'Aardsplijter',       cd: 22, desc: 'Enorme klap die vijanden terugwerpt.' },
  shadowclone:   { name: 'Schaduwklonen',   ult: 'Legioen der Schaduw', cd: 20, desc: 'Driedubbele snelheid en gegarandeerde crits.' },
  solarflare:    { name: 'Zonnevlam',       ult: 'Zonnestorm',         cd: 24, desc: 'Verbrandt alle vijanden in bereik gedurende 3 seconden.' },
  thunderstorm:  { name: 'Onweersbui',      ult: 'Ragnarok',           cd: 26, desc: 'Een storm van bliksems op vijanden in bereik.' },
  phoenixdive:   { name: 'Feniksduik',      ult: 'Zonnefeniks',        cd: 24, desc: 'Een vlammenzee die alles in bereik verbrandt.' },
  singularity:   { name: 'Singulariteit',   ult: 'Gebeurtenishorizon', cd: 25, desc: 'Trekt vijanden terug over het pad en verplettert ze.' },
  orbitalcannon: { name: 'Orbitaal Kanon',  ult: 'Sterrenvernietiger', cd: 28, desc: 'Een gigantische laser op de sterkste vijand van de map.' },
  timerewind:    { name: 'Terugspoelen',    ult: 'Einde der Tijden',   cd: 30, desc: 'Duwt alle vijanden op de map terug en vertraagt ze.' },
  supernova:     { name: 'Supernova',       ult: 'Oerknal',            cd: 32, desc: 'Schade aan alle vijanden op de hele map.' },
  twinstorm:     { name: 'Kogelwervel',     ult: 'Dubbele Draaikolk',  cd: 18, desc: 'Beide blasters draaien 3,5 seconden op volle toeren: 3× zo snel op 3 extra doelen.' },
  bulwark:       { name: 'Schildmuur',      ult: 'Bastion',            cd: 24, desc: 'Zet een lichtmuur op het pad die gewone vijanden 4 seconden tegenhoudt en schade doet.' },
  wishingstar:   { name: 'Wensster',        ult: 'Sterrenregen',       cd: 22, desc: 'Een grote ster valt op de sterkste vijand in bereik en levert extra geld op.' },
  eventhorizon:  { name: 'Zwart Gat',       ult: 'Leegte-Implosie',    cd: 30, desc: 'Opent een zwart gat dat vijanden vasthoudt en verscheurt.' },
  goldrush:      { name: 'Goudkoorts',      ult: 'Beurskrach',         cd: 30, desc: 'Levert direct een zak geld op.' },
  rally:         { name: 'Oppeppen',        ult: 'Wonderkuur',         cd: 24, desc: 'Helden in de buurt worden veel sneller en de basis herstelt wat HP.' },
  headshot:      { name: 'Kopschot',        ult: 'Onzichtbare Kogel',  cd: 20, desc: 'Eén zwaar schot op de sterkste vijand in bereik.' },
  cyclone:       { name: 'Cycloon',         ult: 'Dubbele Tornado',    cd: 24, desc: 'Een tornado raast terug over het pad en blaast vijanden achteruit.' },
  speedforce:    { name: 'Snelheidsstorm',  ult: 'Tijdloze Sprint',    cd: 22, desc: 'Rent in een flits door alle vijanden in de buurt heen.' },
  warcry:        { name: 'Strijdkreet',     ult: 'Voor de Vrijheid!',  cd: 30, desc: 'Alle helden op de map doen 8 seconden 50% meer schade.' },
  dragonbreath:  { name: 'Drakenadem',      ult: 'Inferno',            cd: 26, desc: 'Een zee van drakenvuur over alles in bereik.' },
  missilestorm:  { name: 'Raketregen',      ult: 'Armageddon',         cd: 28, desc: 'Tientallen raketten op vijanden verspreid over de map.' },
  divinelight:   { name: 'Goddelijk Licht', ult: 'Hemelpoort',         cd: 32, desc: 'Halveert de cooldown van andere helden, geeft ze een schadebuff en heelt de basis.' },
  midastouch:    { name: 'Midas-aanraking', ult: 'Gouden Eeuw',        cd: 30, desc: 'Verandert gewone vijanden in bereik in goud: ze sterven en leveren 3× geld op.' },
  spectrum:      { name: 'Spectrumbreuk',   ult: 'Regenboogeinde',     cd: 30, desc: 'Regenboogstralen raken en vertragen elke vijand op de map.' },
  mirrorarmy:    { name: 'Spiegelleger',    ult: 'Oneindige Reflectie', cd: 34, desc: 'Roept spiegelklonen op die tijdelijk op de map meevechten.' },
  judgement:     { name: 'Het Oordeel',     ult: 'Einde der Dagen',    cd: 35, desc: 'Lichtzuilen op elke vijand. Zwakke gewone vijanden worden geëxecuteerd.' },
  bigbang:       { name: 'Oerknal',         ult: 'Nieuwe Schepping',   cd: 40, desc: 'Werpt alle vijanden ver terug en halveert de cooldowns van je helden.' },
};

/* ---------------- Vijanden ---------------- */
const ENEMIES = {
  grunt:    { name: 'Handlanger',  hp: 55,  speed: 1.05, armor: 0, reward: 5,  r: 11, leak: 1, color: '#8b5cf6', desc: 'Standaard handlanger van de schurkenbende.' },
  runner:   { name: 'Sprinter',    hp: 32,  speed: 2.0,  armor: 0, reward: 4,  r: 9,  leak: 1, color: '#22c55e', desc: 'Snel maar zwak.' },
  tank:     { name: 'Pantserbeuk', hp: 240, speed: 0.6,  armor: 4, reward: 12, r: 15, leak: 3, color: '#71717a', desc: 'Zwaar gepantserd: kleine treffers doen weinig.' },
  flyer:    { name: 'Drone',       hp: 48,  speed: 1.4,  armor: 0, reward: 7,  r: 10, leak: 1, color: '#06b6d4', flying: true, desc: 'Vliegt: alleen helden met luchtaanval raken hem.' },
  shield:   { name: 'Schildwacht', hp: 110, shield: 90, speed: 0.9, armor: 1, reward: 10, r: 12, leak: 2, color: '#3b82f6', desc: 'Een energieschild vangt eerst de schade op.' },
  healer:   { name: 'Medibot',     hp: 90,  speed: 0.95, armor: 0, reward: 10, r: 11, leak: 1, color: '#10b981', heal: true, desc: 'Heelt vijanden in de buurt.' },
  splitter: { name: 'Splijter',    hp: 130, speed: 0.85, armor: 1, reward: 9,  r: 13, leak: 2, color: '#f97316', split: 'mini', desc: 'Splitst bij zijn dood in twee kleintjes.' },
  mini:     { name: 'Splintertje', hp: 30,  speed: 1.7,  armor: 0, reward: 2,  r: 7,  leak: 1, color: '#fb923c', hidden: true },
  chaos:    { name: 'Dr. Chaos',   hp: 480, speed: 0.55, armor: 2, reward: 120, r: 24, leak: 20, color: '#84cc16', boss: true, ability: 'summon', desc: 'Gekke wetenschapper die handlangers oproept.' },
  kolos:    { name: 'De Kolos',    hp: 900, speed: 0.4, armor: 10, reward: 160, r: 28, leak: 30, color: '#a8a29e', boss: true, ability: 'stomp', desc: 'Stenen reus. Zijn stamp verdooft helden.' },
  wyrm:     { name: 'Hemelwyrm',   hp: 660, speed: 0.8, armor: 3, reward: 150, r: 22, leak: 25, color: '#0ea5e9', boss: true, flying: true, ability: 'dash', desc: 'Vliegende draak die plots vooruit schiet.' },
  overlord: { name: 'Leegte-Overlord', hp: 1920, speed: 0.45, armor: 6, reward: 300, r: 30, leak: 999, color: '#a21caf', boss: true, ability: 'phases', desc: 'Eindbaas. Krijgt schilden en roept versterking op.' },
};
const ENEMY_FROM_WAVE = { grunt: 1, runner: 3, flyer: 4, tank: 6, splitter: 7, shield: 8, healer: 9 };

/* ---------------- Maps ---------------- */
const MAPS = [
  { id: 'stad', name: 'Havenstad', theme: 'city', reward: 150, hpMult: 1, startCash: 350,
    desc: 'Nachtelijke straten vol schurken. Een lange route: ideaal om te leren.',
    pool: ['grunt', 'runner', 'tank', 'flyer'], bosses: ['chaos'], finalBoss: 'kolos',
    path: [[-1, 3], [6, 3], [6, 10], [13, 10], [13, 4], [19, 4], [19, 11], [24, 11]] },
  { id: 'bos', name: 'Fluisterbos', theme: 'forest', reward: 220, hpMult: 1.3, startCash: 450,
    desc: 'Kronkelende paden tussen oude bomen. Medibots houden de bende op de been.',
    pool: ['grunt', 'runner', 'flyer', 'healer', 'splitter'], bosses: ['chaos', 'wyrm'], finalBoss: 'wyrm',
    path: [[-1, 7], [4, 7], [4, 2], [10, 2], [10, 12], [15, 12], [15, 6], [20, 6], [20, 2], [24, 2]] },
  { id: 'woestijn', name: 'Zonnevlakte', theme: 'desert', reward: 300, hpMult: 1.65, startCash: 600,
    desc: 'Een slingerend spoor door het zand. Zwaar gepantserde colonnes.',
    pool: ['grunt', 'runner', 'tank', 'shield', 'splitter'], bosses: ['chaos', 'kolos'], finalBoss: 'kolos',
    path: [[3, -1], [3, 11], [8, 11], [8, 3], [13, 3], [13, 11], [18, 11], [18, 3], [21, 3], [21, 15]] },
  { id: 'bergen', name: 'IJspiek', theme: 'snow', reward: 400, hpMult: 2.1, startCash: 750,
    desc: 'Haarspeldbochten op een besneeuwde berg. Veel drones in de lucht.',
    pool: ['grunt', 'tank', 'shield', 'flyer', 'healer'], bosses: ['kolos', 'wyrm'], finalBoss: 'wyrm',
    path: [[-1, 2], [20, 2], [20, 6], [3, 6], [3, 10], [20, 10], [20, 13], [24, 13]] },
  { id: 'neo', name: 'Neo-Stad 2099', theme: 'future', reward: 520, hpMult: 2.6, startCash: 950,
    desc: 'Neonlicht en hoverbanen. Alle vijandtypes, en de Leegte-Overlord wacht.',
    pool: ['grunt', 'runner', 'tank', 'flyer', 'shield', 'healer', 'splitter'], bosses: ['chaos', 'wyrm', 'kolos'], finalBoss: 'overlord',
    path: [[12, -1], [12, 3], [4, 3], [4, 8], [9, 8], [9, 12], [16, 12], [16, 7], [20, 7], [20, 3], [24, 3]] },
  { id: 'vulkaan', name: 'Magmakern', theme: 'volcano', reward: 680, hpMult: 3.2, startCash: 1200,
    desc: 'Een kort pad door kokende lava. Alleen voor de sterkste teams.',
    pool: ['grunt', 'runner', 'tank', 'flyer', 'shield', 'healer', 'splitter'], bosses: ['kolos', 'wyrm', 'chaos'], finalBoss: 'overlord',
    path: [[-1, 12], [5, 12], [5, 4], [11, 4], [11, 9], [17, 9], [17, 2], [24, 2]] },
];

const DIFFS = [
  { id: 'easy',      name: 'Makkelijk',   waves: 15, hp: 0.75, speed: 1,    baseHp: 150, cash: 100, reward: 0.6 },
  { id: 'normal',    name: 'Normaal',     waves: 20, hp: 1,    speed: 1,    baseHp: 100, cash: 0, reward: 1 },
  { id: 'hard',      name: 'Moeilijk',    waves: 25, hp: 1.45, speed: 1.08, baseHp: 75,  cash: 0, reward: 1.8 },
  { id: 'nightmare', name: 'Nachtmerrie', waves: 30, hp: 2.1,  speed: 1.15, baseHp: 50,  cash: 0, reward: 2.9 },
];

/* ---------------- Economie ----------------
   In-match geld (killMult, waveBonus) en munten na een potje (coin*). Alles schaalt met map.reward × moeilijkheid. */
const ECONOMY = {
  killMult: 1.25,            // extra speldgeld per kill
  waveBonusBase: 36, waveBonusPerWave: 10,
  coinPerWave: 0.035,        // munten per gehaalde golf, als deel van de basisbeloning
  coinWaveGrowth: 0.05,      // latere golven zijn meer waard (+5% per golf)
  coinPerBoss: 0.1, winBonus: 1.6, firstClear: 1.5,
};
function matchRewards(map, diffIdx, waves, bossKills, win, firstClear) {
  const E = ECONOMY, base = map.reward * DIFFS[diffIdx].reward;
  let waveCoins = 0; for (let i = 1; i <= waves; i++) waveCoins += base * E.coinPerWave * (1 + E.coinWaveGrowth * (i - 1));
  const rows = [[`Golven gehaald (${waves})`, Math.round(waveCoins)], [`Bazen verslagen (${bossKills})`, bossKills * Math.round(base * E.coinPerBoss)]];
  if (win) rows.push(['Map voltooid', Math.round(base * E.winBonus)]);
  if (firstClear) rows.push(['Eerste keer gehaald', Math.round(base * E.firstClear)]);
  return { rows, total: rows.reduce((t, r) => t + r[1], 0) };
}
function bossCount(diffIdx) { const w = DIFFS[diffIdx].waves; return Math.floor((w - 1) / 5) + 1; }

/* ---------------- Gacha's ---------------- */
const GACHAS = [
  { id: 'basic', name: 'Basic Gacha', color: '#a3acb9', price: 100, desc: 'Normale helden om je team mee te starten.',
    rates: { common: 58, uncommon: 30, rare: 10, epic: 2 }, guarantee10: 'rare', unlock: null },
  { id: 'rare', name: 'Rare Gacha', color: '#38bdf8', price: 320, desc: 'Betere helden, met een kleine kans op Legendary en Mythic.',
    rates: { uncommon: 34, rare: 44, epic: 17, legendary: 4.5, mythic: 0.5 }, guarantee10: 'epic', unlock: { map: 'stad', diff: 1 } },
  { id: 'event', name: 'Event Gacha', color: '#ff4f8b', price: 550, desc: 'Tijdelijk: uitgelichte helden hebben een verhoogde kans.',
    rates: { rare: 44, epic: 36, legendary: 15, mythic: 4, exotic: 0.9, ultra: 0.1 }, guarantee10: 'epic', unlock: { map: 'bos', diff: 1 }, event: true },
  { id: 'legendary', name: 'Legendary Gacha', color: '#fbbf24', price: 950, desc: 'Zeer zeldzame helden met een vaste Mythic-kans van 5%.',
    rates: { rare: 29, epic: 44, legendary: 20.5, mythic: 5, exotic: 1.2, ultra: 0.3 }, guarantee10: 'legendary', unlock: { map: 'woestijn', diff: 1 }, pity: { n: 60, rarity: 'mythic', key: 'pity' } },
  { id: 'cosmic', name: 'Kosmische Gacha', color: '#a78bfa', price: 2000, desc: 'De beste kans op Exotic en Ultra helden, de zeldzaamste van allemaal.',
    rates: { legendary: 62, mythic: 28, exotic: 8, ultra: 2 }, guarantee10: 'mythic', unlock: { map: 'neo', diff: 1 }, pity: { n: 40, rarity: 'exotic', key: 'pityCosmic' } },
];
/* Events wisselen elke week. Voeg hier nieuwe events toe. */
const EVENTS = [
  { name: 'Kosmische Storm', featured: ['kosmos', 'storm', 'nova'] },
  { name: 'Vuur & Schaduw', featured: ['feniks', 'schaduw', 'leegte'] },
  { name: 'Tijd & Zwaartekracht', featured: ['tijd', 'grav', 'zon'] },
  { name: 'Goud & Glorie', featured: ['midas', 'banier', 'draak', 'munt'] },
  { name: 'Hemelse Orde', featured: ['engel', 'genesis', 'flits', 'mecha'] },
  { name: 'Sterke Start', featured: ['sterrenkind', 'schildmaagd', 'tweeling'] },
  { name: 'Prismastorm', featured: ['prisma', 'fantoom', 'omega', 'sluip'] },
];
